import type { Metadata } from "next";
import LegalPage from "@/components/sections/LegalPage";

export const metadata: Metadata = {
  title: "Privacy Policy — LUMA",
  description: "How LUMA handles data, what we collect, what we don't, and what stays on-chain.",
};

const SECTIONS = [
  {
    heading: "Our Approach to Privacy",
    body: [
      "LUMA is designed to minimise the data it touches. The Protocol runs on public blockchains — transactions, vault balances, and share distributions are visible to anyone by design. We do not operate a traditional backend, do not require account registration, and do not link on-chain addresses to personal identities.",
      "This policy explains what limited data the frontend interface may process, how we handle it, and what rights you have.",
    ],
  },
  {
    heading: "Data We Do Not Collect",
    body: [
      "We do not collect names, email addresses, phone numbers, or government-issued ID. We do not require login, OAuth, or social sign-in of any kind. We do not build user profiles, track behaviour across sessions, or sell data to third parties — ever.",
      "We do not store private keys, seed phrases, or wallet credentials. Wallet connections are handled client-side through your own wallet software. LUMA never has access to your keys.",
    ],
  },
  {
    heading: "Data the Frontend May Process",
    body: [
      "When you use the LUMA interface your browser may send standard HTTP request data — IP address, browser type, and referring URL — to our hosting infrastructure. This data is used solely for availability monitoring and abuse prevention. It is not retained beyond 30 days and is never used for advertising.",
      "If you connect a wallet, your public address is read client-side to display your on-chain positions. This address is not stored on our servers. It is submitted to the blockchain when you sign transactions — that is inherent to how blockchains work and is not within our control.",
    ],
  },
  {
    heading: "On-Chain Data",
    body: "All transactions you execute via the Protocol — minting agents, calling inference, buying or selling ShareTokens — are recorded permanently on a public blockchain. This data is immutable and publicly visible. No privacy policy can change the nature of public blockchains. If you require privacy for on-chain activity, use appropriate tools before interacting with the Protocol.",
  },
  {
    heading: "Agent Outputs and Inference Receipts",
    body: [
      "Agent inference responses are delivered directly to the caller and attested by the TEE (Trusted Execution Environment). LUMA does not log, store, or have access to the content of inference requests or responses.",
      "Signed receipts are generated by the TEE and stored locally by the caller. They are not transmitted to or stored by LUMA.",
    ],
  },
  {
    heading: "Cookies and Analytics",
    body: "The LUMA interface uses no third-party analytics, tracking pixels, or advertising cookies. We may use minimal first-party session data to maintain interface state (e.g. which step of the launch wizard you are on). This data lives in your browser only and is never transmitted to our servers.",
  },
  {
    heading: "Third-Party Services",
    body: [
      "The interface may load fonts from Google Fonts and connect to public RPC endpoints for blockchain data. These services have their own privacy policies. We select providers that offer strong data minimisation practices, but we cannot guarantee their practices.",
      "We do not embed social media trackers, advertising SDKs, or data broker scripts.",
    ],
  },
  {
    heading: "Data Retention",
    body: "Because we collect almost nothing, there is almost nothing to retain or delete. Any server-side request logs are purged on a rolling 30-day basis. If you want your wallet address dissociated from any cached frontend state, clearing your browser storage is sufficient.",
  },
  {
    heading: "Children",
    body: "The Protocol is not directed at persons under the age of 18. We do not knowingly process data from minors. If you believe a minor has interacted with the Protocol, contact us and we will take appropriate steps.",
  },
  {
    heading: "Changes to This Policy",
    body: "We may update this policy as the Protocol evolves. Changes will be posted on this page with an updated date. Material changes will be announced via @luma_protocol on X.",
  },
  {
    heading: "Contact",
    body: "Privacy questions? Reach us at @luma_protocol on X. We take privacy seriously and will respond promptly.",
  },
];

export default function PrivacyPage() {
  return (
    <LegalPage
      title="Privacy Policy"
      subtitle="LUMA is built to know as little about you as possible. This policy explains what limited data the interface processes, what lives on-chain by necessity, and what we will never do with your information."
      lastUpdated="October 2026"
      sections={SECTIONS}
    />
  );
}
